name: Build and Test

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Get latest commit
        run: git pull --rebase
      - name: Clean Install
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Stop pm2
        run: pm2 stop npm
      - name: Start pm2
        run: pm2 start npm -- start
  # test:
  #   runs-on: self-hosted

  #   steps:
  #     - run: npm ci
      # - run: npm test
