name: Build and Test

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - run: npm ci
             npm run build
             pm2 stop npm
             pm2 start npm -- start
  # test:
  #   runs-on: self-hosted

  #   steps:
  #     - run: npm ci
      # - run: npm test
